---
- name: Install Docker dependencies
  apt:
    name: "{{ docker_dependencies }}"
    state: present
    update_cache: yes

- name: Create keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker
  service:
    name: docker
    enabled: true
    state: started
